services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./dockerfiles/front/Dockerfile
    tty: true
    volumes:
      - ./front:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "./wait-for-back.sh npm run dev"
    ports:
      - "3000:3000"
    
  back:
    container_name: back
    build:
      context: .
      dockerfile: ./dockerfiles/back/Dockerfile
    tty: true
    volumes:
      - ./back:/app
      - ${DOWNLOAD_DIR}:${SAVE_DIR}
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"