services:
  front:
    container_name: front
    image: anonymize-ecg-front:amd64
    build:
      context: .
      dockerfile: ./setup/Dockerfile.front
    platform: linux/amd64
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "./wait-for-back.sh npm run dev"
    ports:
      - "3000:3000"
    
  back:
    container_name: back
    image: anonymize-ecg-back:amd64
    build:
      context: .
      dockerfile: ./setup/Dockerfile.back
    platform: linux/amd64
    tty: true    
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"